# A TOML plugin for proto:
# https://moonrepo.dev/docs/proto/plugins#toml-plugin

name = "moonx"
type = "cli"

[platform.linux-x64]
bin-path = "moonx"
download-file = "linux-x64"
checksum-file = "checksum-linux-x64.txt"

[platform.linux-arm64]
bin-path = "moonx"
download-file = "linux-arm64"
checksum-file = "checksum-linux-arm64.txt"

[platform.macos-x64]
bin-path = "moonx"
download-file = "darwin-x64"
checksum-file = "checksum-darwin-x64.txt"

[platform.macos-arm64]
bin-path = "moonx"
download-file = "darwin-arm64"
checksum-file = "checksum-darwin-arm64.txt"

[install]
download-url = "https://github.com/maastrich/moonx/releases/download/v{version}/{download_file}"
checksum-url = "https://github.com/maastrich/moonx/releases/download/v{version}/{checksum_file}"
# No unpacking needed since binaries are distributed directly
unpack = false

[resolve]
git-url = "https://github.com/maastrich/moonx"
