# A TOML plugin for proto:
# https://moonrepo.dev/docs/proto/plugins#toml-plugin

name = "moonx"
type = "cli"

[platform.linux]
download-file = "linux-{arch}"
checksum-file = "checksum-linux-{arch}.txt"

[platform.macos]
download-file = "darwin-{arch}"
checksum-file = "checksum-darwin-{arch}.txt"

[install]
# No unpacking needed since binaries are distributed directly
unpack = false

[install.arch]
aarch64 = "arm64"
x86_64 = "x64"

[install.exes]
moonx = { primary = true }

[resolve]
git-url = "https://github.com/maastrich/moonx"
