name: deploy

on:
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    name: build and deploy
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - run: bun install
      - run: bun run prettier
      - run: bun run build
      - run: bun run sort --check
      - run: bun run semver-check
