name: check

on:
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    name: check code style and build
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1
      - run: bun install
      - run: bun run prettier
      - run: bun run build
      - run: bun run sort --check
      - run: bun run semver-check
